#!/bin/bash

battery_count=0
e_now_total=0
e_full_total=0

charging_status_0=""
charging_status_1=""

# BAT0
if [ -d "/sys/class/power_supply/BAT0" ]; then
    e_now_0=$(cat /sys/class/power_supply/BAT0/energy_now)
    e_full_0=$(cat /sys/class/power_supply/BAT0/energy_full)
    charging_status_0=$(cat /sys/class/power_supply/BAT0/status)

    e_now_total=$(( e_now_total + e_now_0 ))
    e_full_total=$(( e_full_total + e_full_0 ))
    battery_count=$((battery_count + 1))
fi

# BAT1
if [ -d "/sys/class/power_supply/BAT1" ]; then
    e_now_1=$(cat /sys/class/power_supply/BAT1/energy_now)
    e_full_1=$(cat /sys/class/power_supply/BAT1/energy_full)
    charging_status_1=$(cat /sys/class/power_supply/BAT1/status)

    e_now_total=$(( e_now_total + e_now_1 ))
    e_full_total=$(( e_full_total + e_full_1 ))
    battery_count=$((battery_count + 1))
fi

# Compute weighted mean capacity
mean_capacity=0
if [ $battery_count -gt 0 ]; then
    mean_capacity=$(( e_now_total * 100 / e_full_total ))
fi

# Choose icon
if [ $mean_capacity -ge 80 ]; then
    battery_icon=""
elif [ $mean_capacity -ge 60 ]; then
    battery_icon=""
elif [ $mean_capacity -ge 30 ]; then
    battery_icon=""
elif [ $mean_capacity -ge 10 ]; then
    battery_icon=""
else
    battery_icon=""
fi

# Output with GTK Pango
if [[ "$charging_status_0" == "Charging" ]] || [[ "$charging_status_1" == "Charging" ]]; then
    echo -n "<span foreground='#C3E88D'>$battery_icon</span>  $mean_capacity%"
else
    if [ $mean_capacity -eq 0 ]; then
        echo -n ""
    else
        echo -n "<span foreground='#C3E88D'>$battery_icon</span> $mean_capacity%"
    fi
fi
