
[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = 'helix "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]


[open]
prepend_rules = [
	{ name = "*.json", use = "edit" },
	{ name = "*.sh", use = "edit" },
	{ name = "*.toml", use = "edit" },
	{ name = "*.y*ml", use = "edit" },
	{ name = "*config", use = "edit" },
	{ name = "*.cfg", use = "edit" },
	{ name = "*env", use = "edit" },
	{ name = "*.d", use = "edit" },
	{ name = "*.md", use = "edit" },
	{ name = "*.txt", use = "edit" },
	{ name = ".zsh*", use = "edit" },
	{ name = "*.ini", use = "edit" },
	{ name = "*.lua", use = "edit" },
	{ name = "*.xml", use = "edit" },
	{ name = "*.log", use = "edit" },
# open with normal / gnome / kde
	{ name = "*.ods", use = "open" },
	{ name = "*.pdf", use = "open" },
# open with multimedia player
	{ name = "*.mp3", use = "play" },
	{ name = "*.mp4", use = "play" },
	{ name = "*.mkv", use = "play" },

	# Only Decompress and Unarchive. Do not open
	{ mime = "application/{,g}zip", use = [ "extract" ] },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract" ] }
]
append_rules = [
	{ name = "*", use = "edit" },
]
