# Set opacity for WezTerm
windowrule {
  name = wezterm-opacity
  match:class = (?i).*wezterm.*

  opacity = 0.9 override 0.75 override 1
}

# Fix dragging issues with XWayland windows
windowrule {
  name = xwayland-drag-fix
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = on
  match:fullscreen = 0

}
